# Generated by Django 5.0.6 on 2025-03-28 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=70)),
                ('description', models.CharField(max_length=250)),
                ('average_rank', models.FloatField()),
                ('count_rank', models.IntegerField()),
                ('type_game', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=330)),
                ('average_rank', models.FloatField()),
                ('count_rank', models.IntegerField()),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section')),
            ],
        ),
    ]
