# Generated by Django 5.0.6 on 2025-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_section_name_alter_section_type_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type_game',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='type_game',
            field=models.IntegerField(choices=[(0, 'No game'), (1, 'Game 1'), (2, 'Game 2'), (3, 'Game 3')], default=0),
        ),
    ]
