# Generated by Django 5.0.6 on 2025-03-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exhibit_average_rank_alter_exhibit_count_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='average_rank',
        ),
        migrations.RemoveField(
            model_name='section',
            name='count_rank',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
