# Generated by Django 5.0.6 on 2025-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_section_average_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
