# Generated by Django 5.0.6 on 2025-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_exhibit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
