# Generated by Django 5.1.7 on 2025-04-01 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='type_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.game'),
        ),
    ]
