# Generated by Django 5.1.7 on 2025-04-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_exhibit_type_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.game'),
        ),
    ]
